"""Words copied from Theorems 3 and 5 of the manuscript.

The strings are split over lines only for readability.  ``parse_word`` removes
whitespace before they are used.
"""

from __future__ import annotations

THEOREM_3_SYMMETRIC_PIECE = "CBDCDCDCBADCBA"

THEOREM_3_LENGTH_40 = "DABCACDACDBCABCACDBACDCBDCBCABDCACABDCBC"

THEOREM_5_WORDS: dict[str, str] = {
    "9_35": """
        ABCABCDCABCDCDCBCDCABCDCACDCA
        BCABCDCBCDCABCDCABCDCABCDCBCD
        CDCABCABCDCABCDCACDCABCABCDCA
        BCDCABCABCDCACDCABCDCACDCABCA
        BCDCABCDCABCDCABCDCABCDCABCDC
        BCDCABCDCABCDCABCDCABCDCABCDC
    """,
    "9_40": """
        ABCABCDCBCDCBCACDCABCDCABCDCABCDCACDC
        ABCDCABCDCABCDCABCDCACDCABCDCABCDCABCDC
        BCDCABCDCABCDCDCABCDCABCDCBCDCABCDCABCDC
    """,
    "9_41": """
        ABCDCABCDCABCDCDCABCDCABCDCABCD
        CABCDCABCDCABCDCABCDCABCDCBCDCA
        BCDCABCDCABCDCACDCDCABCDCABCDCA
        BCABCDCABCDCABCDCABCDCDCABCDCAB
        CDCACDCABCDCABCDCABCDCDCABCDCBC
        DCABCDCABCDCBCDCABCDCABCABCDCDC
    """,
    "9_47": """
        ACDCBCDCABCDCABCDCABCDCABCABCDCABCDCABCDCABCDCABCD
        CBCDCABCDCABCDCABCABCDCABCDCABCDCABCDCABCDCABCDCAB
        CABCDCABCDCABCDCABCDCABCDCABCDCABCDCABCDCBCDCABCDC
        ABCDCABCDCABCDCABCDCABCABCDCABCDCABCDCABCDCABCDCAB
        CDCBCDCABCDCABCDCABCDCABCDCABCDCABCDCABCDCABCABCDC
    """,
}

THEOREM_5_STATED_LENGTHS: dict[str, int] = {
    "9_35": 174,
    "9_40": 116,
    "9_41": 186,
    "9_47": 250,
}
